version: '2.1'

services:
  angular_course:
    container_name: angular
    build: ./front
    environment:
      NODE_ENV: development
    volumes:
      - ./front:/usr/src/app
    ports:
      - 3010:3010
      - 9005:9005
    stdin_open: true