version: '3.7'

services:
  angular:
    container_name: angular
    build: ./front
    environment:
      NODE_ENV: development
    volumes:
      - ./front:/usr/src/app
    ports:
      - 3010:3010
      - 9005:9005
    stdin_open: true
  python:
    container_name: python
    build: ./back
    env_file: .env.python
    volumes:
      - ./back:/usr/src/app
    ports:
      - 3011:3011
    links:
      - mongo
    stdin_open: true
  mongo:
    image: mongo
    hostname: mongo
    healthcheck:
      test: ["CMD","mongo", "--quiet", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
    ports:
      - 27017:27017